import 'dart:math' as math;
import 'dart:async';
import 'dart:io';

import 'package:alfred/alfred.dart';
import 'package:pennyworth/pennyworth.dart';

// This file is generated by [Pennyworth Builder](https://github.com/d-markey/pennyworth_builder) according to annotations in source code.
// Annotations are provided by [Pennyworth](https://github.com/d-markey/pennyworth), and interpreted by Pennyworth Builder.
// Pennyworth must be installed as a regular dependency to your project, while Pennyworth Builder is just a development dependency.
// Annotations are not interpreted dynamically (at runtime). Code generation with [build_runner](https://pub.dev/packages/build_runner) is mandatory.
//
// To generate the source code from Pennyworth annotations, run:
//
//      dart run build_runner build
//
part 'math_service.g.dart';

@RestService('/', tags: ['MATH'])
class MathService extends NestedOpenApi {
  MathService();

  @RestOperation(uri: '/add/:a:int/:b:int', summary: 'Returns a + b')
  Future<int> add(int a, int b) async {
    return a + b;
  }

  @RestOperation(uri: '/sub/:a:int/:b:int', summary: 'Returns a - b')
  Future<int> sub(int a, int b) async {
    return a - b;
  }

  @RestOperation(uri: '/mul/:a:int/:b:int', summary: 'Returns a * b')
  Future<int> mul(int a, int b) async {
    return a * b;
  }

  @RestOperation(uri: '/div/:a:int/:b:int', summary: 'Returns a / b')
  Future<double> div(int a, int b) async {
    if (b == 0) throw AlfredException(403, 'Division by 0');
    return a / b;
  }

  @RestOperation(uri: '/sqrt/:x:double', summary: 'Returns sqrt(x)')
  Future<double> sqrt(double x) async {
    if (x < 0) throw AlfredException(403, 'Square root of negative number');
    return math.sqrt(x);
  }

  @override
  List<OpenApiRoute> mount(
          NestedRoute parentRoute, OpenApiService openApiService) =>
      parentRoute.mount_MathService(this, openApiService);
}
