name: pennyworth
description: Alfred service & OpenApi documentation generator
version: 0.1.0-beta
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  alfred: ^1.1.0
  async: ^2.10.0
  meta: ^1.9.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
